name: yusql-trigger

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: wakeup render site
        run: node src/yusql-trigger.js

      - name: Update README
        run: |
          git config --global user.email "trieuvanbd123@gmail.com"
          git config --global user.name "yuran1811"
          git add .
          git commit -m "chore: update [yusql] status" || echo "No changes to commit"
          git push
